INSERT INTO EXTRACTORS (ID, NAME, HOSTNAME, JMS_PROFILE_ID, DOCUMENT_EXTRACTOR_COUNT, MIN_HEAP_MEMORY, CONFIG_RELOAD_INTERVAL, CREATED_ON)
VALUES (id, 'Content Extractor (@hostname)', '@hostname', JMS_ID, 4, 512, 300, CONVERT (datetime2,GETDATE(),120));
-EOL-
