INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (id, 1512010900000006, 1, 'License Expiry Date', 'license.expiryDate', 'expiry_date', 'License Expiry Date', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (id, 1512010900000006, 2, 'Licensed Data Volume', 'license.dataSize', 'data_size', 'Licensed Data Volume in GB.', CONVERT (datetime2,GETDATE(),120))
-EOL-