INSERT INTO RULE_ENGINES (ID, NAME, HOSTNAME, ON_DEMAND_INTERVAL, SCHEDULED_INTERVAL, ON_DEMAND_POOL_SIZE, SCHEDULED_POOL_SIZE, CONFIG_RELOAD_INTERVAL, CREATED_ON)
VALUES (id, 'RuleEngine (@hostname)', '@hostname', 5, 60, 2, 4, 300, CONVERT (datetime2,GETDATE(),120));
-EOL-