DROP SEQUENCE [dbo].[WATCHERS_SEQ]
-EOL-
DROP SEQUENCE [dbo].[EXTRACTORS_SEQ]
-EOL-
DROP SEQUENCE [dbo].[RULE_ENGINES_SEQ]
-EOL-
DROP SEQUENCE [dbo].[HEARTBEATS_SEQ]
-EOL-
DROP TRIGGER [dbo].[trgCleanUpWatcherEventLog], [dbo].[trgCleanUpExtractorEventLog], [dbo].[trgCleanUpRuleEngineEventLog]
-EOL-
DROP TRIGGER [dbo].[trgCleanUpWatcherExecutionWindow], [dbo].[trgCleanUpExtractorExecutionWindow], [dbo].[trgCleanUpRuleEngineExecutionWindow]
-EOL-
DROP TRIGGER [dbo].[trgCleanUpWatcherHeartbeat], [dbo].[trgCleanUpExtractorHeartbeat], [dbo].[trgCleanUpRuleEngineHeartbeat]
-EOL-
DROP TRIGGER [dbo].[trgUpdateRuleEngineRule]
-EOL-
DROP TABLE [dbo].[EVENT_LOGS]
-EOL-
DROP TABLE [dbo].[HEARTBEATS]
-EOL-
ALTER TABLE [dbo].[RULES] ADD [VERSION] [int] NOT NULL DEFAULT 1, [REPOSITORY_TYPE] [nvarchar](30) NOT NULL DEFAULT('SHARED FOLDER')
-EOL-
ALTER TABLE [dbo].[RULE_EXECUTIONS] ADD [RULE_VERSION] [int] 
-EOL-
ALTER TABLE [dbo].[DOCUMENT_RECORDS] ADD [FILE_ID] [nvarchar](100) NULL, [REPOSITORY_TYPE] [nvarchar](30) NOT NULL DEFAULT('SHARED FOLDER')
-EOL-
ALTER TABLE [dbo].[EXECUTION_WINDOW_ASSOCIATIONS] ADD [COMPONENT_ID] [bigint] NOT NULL DEFAULT 0
-EOL-
CREATE TABLE [dbo].[HEARTBEATS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[COMPONENT_ID] [bigint] NOT NULL,
	[COMPONENT_TYPE] [nchar](1) NOT NULL,
	[LAST_HEARTBEAT] [bigint] NOT NULL DEFAULT 0,
	[CREATED_ON] [datetime2](7) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[RULE_HISTORIES](
	[ID] [bigint] NOT NULL,
	[RULE_ID] [bigint] NOT NULL,
	[RULE_VERSION] [int] NOT NULL,
	[SUMMARY] [nvarchar](max) NOT NULL,
	[CREATED_BY] [nvarchar](100) NULL,
	[CREATED_ON] [datetime2](7) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[METADATA_FIELDS](
	[FIELD_NAME] [nvarchar](100) NOT NULL,
	[DISPLAY_ORDER] [int] NOT NULL,
	[DISPLAY_NAME] [nvarchar](100) NOT NULL,
	[UI_DATA_TYPE] [nvarchar](10) NOT NULL,
	[STORAGE_DATA_TYPE] [nvarchar](10) NOT NULL,
	[VISIBLE] [bit] NOT NULL,
	PRIMARY KEY CLUSTERED(
		[FIELD_NAME] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[EVENT_LOGS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[COMPONENT_NAME] [nvarchar](100) NOT NULL,
	[STAGE] [nchar](4) NOT NULL,
	[FILE_ID] [nvarchar](100) NULL,
	[REPOSITORY_TYPE] [nvarchar](30) NULL,
	[FILE_PATH] [nvarchar](1024) NULL,
	[FILE_NAME] [nvarchar](450) NULL,
	[RULE_ID] [bigint] NULL,
	[RULE_NAME] [nvarchar](320) NULL,
	[RULE_EXECUTION_ID] [bigint] NULL,
	[RULE_EXECUTION_TYPE] [nchar](1) NULL,
	[ACTION_PLUGIN_ID] [bigint] NULL,
	[ACTION_NAME] [nvarchar](100) NULL,
	[ACTION_ID] [bigint] NULL,
	[CATEGORY] [nchar](1) NOT NULL,
	[STATUS] [nchar](1) NOT NULL,
	[MESSAGE_CODE] [nvarchar](50) NOT NULL,
	[MESSAGE_PARAM] [nvarchar](4000) NULL,
	[TIMESTAMP] [bigint] NOT NULL DEFAULT 0,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[EVENT_LOG_ARCHIVES](
	[ID] [bigint] NOT NULL,
	[COMPONENT_NAME] [nvarchar](100) NOT NULL,
	[STAGE] [nchar](4) NOT NULL,
	[FILE_ID] [nvarchar](100) NULL,
	[REPOSITORY_TYPE] [nvarchar](30) NULL,
	[FILE_PATH] [nvarchar](1024) NULL,
	[FILE_NAME] [nvarchar](450) NULL,
	[RULE_ID] [bigint] NULL,
	[RULE_NAME] [nvarchar](320) NULL,
	[RULE_EXECUTION_ID] [bigint] NULL,
	[RULE_EXECUTION_TYPE] [nchar](1) NULL,
	[ACTION_PLUGIN_ID] [bigint] NULL,
	[ACTION_NAME] [nvarchar](100) NULL,
	[ACTION_ID] [bigint] NULL,
	[CATEGORY] [nchar](1) NOT NULL,
	[STATUS] [nchar](1) NOT NULL,
	[MESSAGE_CODE] [nvarchar](50) NOT NULL,
	[MESSAGE_PARAM] [nvarchar](4000) NULL,
	[TIMESTAMP] [bigint] NOT NULL DEFAULT 0,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[AUTH_HANDLERS] (
	[ID] [bigint] NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[TYPE] [nvarchar](25) NOT NULL,
	[CONFIGURATION_DATA] [nvarchar](4000),
	[USER_ATTRIBUTE_MAPPING] [nvarchar](4000),
	[CREATED_ON] [datetime2](7) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[MODIFIED_ON] [datetime2](7) NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[USERS](
	[ID] [bigint] NOT NULL,
	[USER_TYPE] [nvarchar](1) NOT NULL,
	[USERNAME] [nvarchar](100) NOT NULL,
	[DISPLAY_NAME] [nvarchar](255),
	[FIRST_NAME] [nvarchar](70),
	[LAST_NAME] [nvarchar](35),
	[EMAIL] [nvarchar](320),
	[PASSWORD] [nvarchar](256),
	[ADMIN] [bit] NOT NULL DEFAULT 0,
	[VISIBLE] [bit] NOT NULL DEFAULT 1,
	[ENABLED] [bit] NOT NULL DEFAULT 1,
	[STATUS] [nvarchar](10) NOT NULL DEFAULT 'ACTIVE',
	[AUTH_HANDLER_ID] [bigint],
	[PASSWORD_CHANGED_ON] [bigint],
	[FAILED_ATTEMPT] [int] NOT NULL DEFAULT 0,
	[LOGIN_ON] [bigint],
	[LAST_LOGIN_ON] [bigint],
	[CREATED_ON] [datetime2](7) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[MODIFIED_ON] [datetime2](7) NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT UC_USERNAME UNIQUE ([USERNAME]),
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[REPORTS](
	[ID] [bigint] NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[DESCRIPTION] [nvarchar](1024) NULL,
	[TYPE] [nchar](1) NOT NULL,
	[RANGE] [nvarchar](1024) NOT NULL,
	[EVENT_STATUS] [nchar](1) NOT NULL,
	[DELETED] [bit] NOT NULL DEFAULT 0,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_ON] [datetime2](7) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[MODIFIED_BY] [nvarchar](100) NULL,
	[MODIFIED_ON] [datetime2](7) NULL DEFAULT CURRENT_TIMESTAMP,
	[LAST_ACCESSED_ON] [datetime2](7) NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[REPORT_FILTER_GROUPS](
	[ID] [bigint] NOT NULL,
	[REPORT_ID] [bigint] NOT NULL,
	[DISPLAY_ORDER] [int] NOT NULL,
	[OPERATOR] [nvarchar](3) NULL,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[REPORT_FILTERS](
	[ID] [bigint] NOT NULL,
	[REPORT_FILTER_GROUP_ID] [bigint] NOT NULL,
	[DISPLAY_ORDER] [int] NOT NULL,
	[FIELD_NAME] [nvarchar](100) NOT NULL,
	[OPERATOR] [nvarchar](25) NOT NULL,
	[VALUE] [nvarchar](1024) NOT NULL,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[REPORT_SCHEDULES](
	[ID] [bigint] NOT NULL,
	[REPORT_ID] [bigint] NOT NULL,
	[SCHEDULE_TYPE] [nchar](1) NOT NULL,	
	[EXECUTION_FREQUENCY] [nvarchar](120) NOT NULL,
	[ENABLED] [bit] NOT NULL,
	[EFFECTIVE_FROM] [datetime2](7) NULL,
	[EFFECTIVE_UNTIL] [datetime2](7) NULL,
	[EMAIL_SUBJECT] [nvarchar](1024) NOT NULL,
	[EMAIL_CONTENT] [nvarchar](4000) NOT NULL,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[REPORT_RECIPIENTS](
	[ID] [bigint] NOT NULL,
	[REPORT_SCHEDULE_ID] [bigint] NOT NULL,
	[DISPLAY_ORDER] [int] NOT NULL,
	[FIELD] [nvarchar](3) NOT NULL,
	[EMAIL] [nvarchar](320) NOT NULL,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[REPORT_EXECUTIONS](
	[ID] [bigint] NOT NULL,
	[REPORT_SCHEDULE_ID] [bigint] NOT NULL,
	[REPORT_DOCUMENT] [nvarchar](1024) NULL,
	[STATUS] [nchar](1) NOT NULL,
	[PLAN_TIMESTAMP] [datetime2](7) NOT NULL,
	[START_TIMESTAMP] [datetime2](7) NULL,
	[END_TIMESTAMP] [datetime2](7) NULL,
	[CREATED_ON] [datetime2](7) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[MODIFIED_ON] [datetime2](7) NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
CREATE TABLE [dbo].[ROLLBACK_ERRORS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[REPOSITORY_TYPE] [nvarchar](30) NULL,
	[BACKUP_ABSOLUTE_FILE_PATH] [nvarchar](1024) NULL,
	[TARGET_ABSOLUTE_FILE_PATH] [nvarchar](1024) NOT NULL,
	[RULE_ID] [bigint] NOT NULL,
	[RULE_NAME] [nvarchar](320) NOT NULL,
	[RULE_EXECUTION_ID] [bigint] NOT NULL,
	[RULE_EXECUTION_TYPE] [nchar](1) NOT NULL,
	[ACTION_PLUGIN_ID] [bigint] NULL,
	[ACTION_NAME] [nvarchar](100) NULL,
	[ACTION_ID] [bigint] NULL,
	[ERROR_TYPE] [nchar](1) NOT NULL,
	[MESSAGE] [nvarchar](4000) NULL,
	[TIMESTAMP] [bigint] NOT NULL DEFAULT 0,
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	ON [PRIMARY]
) ON [PRIMARY]
-EOL-
ALTER TABLE [dbo].[REPORT_FILTER_GROUPS] WITH CHECK ADD CONSTRAINT [FK_REPORT_4_REPORT_FILTER_GROUP] FOREIGN KEY([REPORT_ID]) 
REFERENCES [dbo].[REPORTS] ([ID]) ON DELETE CASCADE
-EOL-
ALTER TABLE [dbo].[REPORT_FILTER_GROUPS] CHECK CONSTRAINT [FK_REPORT_4_REPORT_FILTER_GROUP]
-EOL-
ALTER TABLE [dbo].[REPORT_FILTERS] WITH CHECK ADD CONSTRAINT [FK_REPORT_FILTER_GROUP_4_REPORT_FILTER] FOREIGN KEY([REPORT_FILTER_GROUP_ID]) 
REFERENCES [dbo].[REPORT_FILTER_GROUPS] ([ID]) ON DELETE CASCADE
-EOL-
ALTER TABLE [dbo].[REPORT_FILTERS] CHECK CONSTRAINT [FK_REPORT_FILTER_GROUP_4_REPORT_FILTER]
-EOL-
ALTER TABLE [dbo].[REPORT_SCHEDULES] WITH CHECK ADD CONSTRAINT [FK_REPORT_4_REPORT_SCHEDULE] FOREIGN KEY([REPORT_ID]) 
REFERENCES [dbo].[REPORTS] ([ID]) ON DELETE CASCADE
-EOL-
ALTER TABLE [dbo].[REPORT_SCHEDULES] CHECK CONSTRAINT [FK_REPORT_4_REPORT_SCHEDULE]
-EOL-
ALTER TABLE [dbo].[REPORT_RECIPIENTS] WITH CHECK ADD CONSTRAINT [FK_REPORT_SCHEDULE_4_RECIPIENT] FOREIGN KEY([REPORT_SCHEDULE_ID]) 
REFERENCES [dbo].[REPORT_SCHEDULES] ([ID]) ON DELETE CASCADE
-EOL-
ALTER TABLE [dbo].[REPORT_RECIPIENTS] CHECK CONSTRAINT [FK_REPORT_SCHEDULE_4_RECIPIENT]
-EOL-
ALTER TABLE [dbo].[REPORT_EXECUTIONS] WITH CHECK ADD CONSTRAINT [FK_REPORT_SCHEDULE_4_REPORT_EXECUTION] FOREIGN KEY([REPORT_SCHEDULE_ID]) 
REFERENCES [dbo].[REPORT_SCHEDULES] ([ID]) ON DELETE CASCADE
-EOL-
ALTER TABLE [dbo].[REPORT_EXECUTIONS] CHECK CONSTRAINT [FK_REPORT_SCHEDULE_4_REPORT_EXECUTION]
-EOL-
CREATE SEQUENCE [dbo].[RULE_HISTORIES_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[COMPONENTS_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[AUTH_HANDLERS_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[USERS_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[SOURCE_AUTHENTICATION_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[REPORTS_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[REPORT_FILTER_GROUPS_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[REPORT_FILTERS_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[REPORT_SCHEDULES_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[REPORT_EXECUTIONS_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE SEQUENCE [dbo].[REPORT_RECIPIENTS_SEQ] START WITH 101 INCREMENT BY 1 CYCLE
-EOL-
CREATE TRIGGER trgCleanUpWatcherHeartbeat ON [dbo].[WATCHERS]
 AFTER DELETE
 AS
	DECLARE @componentId bigint;

	SELECT @componentId = d.ID FROM DELETED d;

	DELETE FROM HEARTBEATS
	WHERE COMPONENT_ID = @componentId AND COMPONENT_TYPE = 'W'
-EOL-
CREATE TRIGGER trgCleanUpWatcherExecutionWindow ON [dbo].[WATCHERS]
 AFTER DELETE
 AS
	DECLARE @componentId bigint;

	SELECT @componentId = d.ID FROM DELETED d;

	DELETE FROM EXECUTION_WINDOW_ASSOCIATIONS
	WHERE COMPONENT_ID = @componentId AND COMPONENT_TYPE = 'W'
-EOL-
CREATE TRIGGER trgCleanUpExtractorHeartbeat ON [dbo].[EXTRACTORS]
 AFTER DELETE
 AS
	DECLARE @componentId bigint;

	SELECT @componentId = d.ID FROM DELETED d;

	DELETE FROM HEARTBEATS
	WHERE COMPONENT_ID = @componentId AND COMPONENT_TYPE = 'E'
-EOL-
CREATE TRIGGER trgCleanUpExtractorExecutionWindow ON [dbo].[EXTRACTORS]
 AFTER DELETE
 AS
	DECLARE @componentId bigint;

	SELECT @componentId = d.ID FROM DELETED d;

	DELETE FROM EXECUTION_WINDOW_ASSOCIATIONS
	WHERE COMPONENT_ID = @componentId AND COMPONENT_TYPE = 'E'
-EOL-
CREATE TRIGGER trgCleanUpRuleEngineHeartbeat ON [dbo].[RULE_ENGINES]
 AFTER DELETE
 AS
	DECLARE @componentId bigint;

	SELECT @componentId = d.ID FROM DELETED d;

	DELETE FROM HEARTBEATS
	WHERE COMPONENT_ID = @componentId AND COMPONENT_TYPE = 'R'
-EOL-
CREATE TRIGGER trgCleanUpRuleEngineExecutionWindow ON [dbo].[RULE_ENGINES]
 AFTER DELETE
 AS
	DECLARE @componentId bigint;

	SELECT @componentId = d.ID FROM DELETED d;

	DELETE FROM EXECUTION_WINDOW_ASSOCIATIONS
	WHERE COMPONENT_ID = @componentId AND COMPONENT_TYPE = 'R'
-EOL-
CREATE TRIGGER trgUpdateRuleEngineRule ON [dbo].[RULE_ENGINES]
 AFTER DELETE
 AS
	DECLARE @ruleEngineId bigint;

	SELECT @ruleEngineId = d.ID FROM DELETED d;

	UPDATE RULES SET RULE_ENGINE_ID = NULL
	WHERE RULE_ENGINE_ID = @ruleEngineId
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('application_name', 1, 'Application Name', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('author', 2, 'Author', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('category', 3, 'Category', 'STRING', 'STRING', 0)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('comments', 4, 'Comments', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('creation_date_millisecond', 5, 'Creation Date', 'DATE', 'LONG', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('creator', 6, 'Creator', 'STRING', 'STRING', 0)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('description', 7, 'Description', 'STRING', 'STRING', 0)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('from', 8, 'Email Sender', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('to', 9, 'Email Recipient', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('keywords', 10, 'Keywords', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('last_author', 11, 'Last Author', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('last_modified_date_millisecond', 12, 'Last Modified Date', 'DATE', 'LONG', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('page_count', 13, 'Page Count', 'INTEGER', 'INTEGER', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('producer', 14, 'Producer', 'STRING', 'STRING', 0)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('revision_number', 15, 'Revision Number', 'INTEGER', 'INTEGER', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('subject', 16, 'Subject', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('template', 17, 'Template', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('title', 18, 'Title', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('word_count', 19, 'Word Count', 'INTEGER', 'INTEGER', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('site_url', 20, 'Site URL', 'STRING', 'STRING', 0)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('folder_url', 21, 'Folder URL', 'STRING', 'STRING', 0)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('creation_date', 22, 'Creation Date', 'DATE', 'DATE', 0)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('last_modified_date', 23, 'Last Modified Date', 'DATE', 'DATE', 0)
-EOL-
DELETE FROM SYSTEM_CONFIGS WHERE IDENTIFIER = 'w.size.eventToRetain'
-EOL-
DELETE FROM SYSTEM_CONFIGS WHERE IDENTIFIER = 'e.size.eventToRetain'
-EOL-
DELETE FROM SYSTEM_CONFIGS WHERE IDENTIFIER = 'r.size.eventToRetain'
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1705010900000001, 1512010900000001, 9, 'Login URL', 'login.url', 'http://@hostname:8080/cas/login?service=', 'Smart Classifier CAS login URL', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1705010900000002, 1512010900000001, 10, 'Logout URL', 'logout.url', 'http://@hostname:8080/cas/logout?service=', 'Smart Classifier logout redirect URL', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIG_GROUPS (ID, NAME, DESCRIPTION, DISPLAY_ORDER, EDITABLE, CREATED_ON) 
VALUES (1512010900000011, 'Report Log', 'Report log settings', 11, 1, CONVERT (datetime2,'2015-12-01 09:00:00.000',120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON)
VALUES (1512010900000059, 1512010900000003, 3, 'Document last modified date split time', 'w.split.lastModifiedDate', '15', 'Split time to fire document changed event since document''s last modified date. (In second)', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000043, 1512010900000011, 1, 'Document added event', 'report.log.enable.documentAdded', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000044, 1512010900000011, 2, 'Document updated event', 'report.log.enable.documentUpdated', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000045, 1512010900000011, 3, 'Document removed event', 'report.log.enable.documentRemoved', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000046, 1512010900000011, 4, 'Document extraction successful event', 'report.log.enable.extractionSuccess', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000047, 1512010900000011, 5, 'Document extraction failed event', 'report.log.enable.extractionFailed', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000048, 1512010900000011, 6, 'Document indexed successful event', 'report.log.enable.indexingSuccess', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000049, 1512010900000011, 7, 'Document indexing failed event', 'report.log.enable.indexingFailed', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000050, 1512010900000011, 8, 'Rule execution start event', 'report.log.enable.ruleExecutionStart', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000051, 1512010900000011, 9, 'Rule execution end event', 'report.log.enable.ruleExecutionEnd', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000052, 1512010900000011, 10, 'Rule execution success event', 'report.log.enable.ruleExecutionSuccess', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000053, 1512010900000011, 11, 'Rule execution failed event', 'report.log.enable.ruleExecutionFailed', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000054, 1512010900000011, 12, 'Action execution success event', 'report.log.enable.actionExecutionSuccess', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000055, 1512010900000011, 13, 'Action execution failed event', 'report.log.enable.actionExecutionFailed', 'true', 'Set true to enable logging', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000056, 1512010900000011, 14, 'Event retention period (in days)', 'report.log.retention.day', '90', 'Event record older than this value will be moved to archive table', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000057, 1512010900000004, 5, 'Document extraction retry count (upon failed attempt)', 'e.count.failedExtractionRetry', '3', 'Retry count when document extraction has failed upon received extraction request.', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO SYSTEM_CONFIGS (ID, SYSTEM_CONFIG_GROUP_ID, DISPLAY_ORDER, LABEL, IDENTIFIER, VALUE, DESCRIPTION, CREATED_ON) 
VALUES (1512010900000058, 1512010900000004, 6, 'Document extraction retry interval (upon failed attempt)', 'e.interval.failedExtractionRetry', '5', 'Document extraction retry interval when document extraction has failed. (In second)', CONVERT (datetime2,GETDATE(),120))
-EOL-
INSERT INTO USERS (ID, USER_TYPE, USERNAME, DISPLAY_NAME, LAST_NAME, PASSWORD, ADMIN, VISIBLE, ENABLED, STATUS, CREATED_ON) 
VALUES (1612300900000001, 'I', 'Administrator', 'Administrator', 'Administrator', 'c9808cfe7a98acf1088e791b41bdaeed', 1, 1, 1, 'ACTIVE', CONVERT (datetime2,GETDATE(),120))
-EOL-
UPDATE ACTION_PLUGIN_PARAMS 
SET DISPLAY_ORDER = 2 WHERE ID = 1512301609000001 AND ACTION_PLUGIN_ID = 1512300900000009
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER) 
VALUES (1512301609000002, 1512300900000009, 1, 'P', 0, 0, 'Boolean', 'Perform on security enabled metadata', 'edit-encrypted-document', 0)
-EOL-
UPDATE ACTION_PLUGIN_PARAMS 
SET DISPLAY_ORDER = 2 WHERE ID = 1512301608000001 AND ACTION_PLUGIN_ID = 1512300900000008
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER) 
VALUES (1512301608000002, 1512300900000008, 1, 'P', 0, 0, 'Boolean', 'Perform on security enabled metadata', 'edit-encrypted-document', 0)
-EOL-
UPDATE SYSTEM_CONFIGS 
SET VALUE = 'id file_id directory folder_url document_name repository_type file_type creation_date last_modified_date author last_author site_url serverrelativeurl_t repository_path last_modified_date_millisecond' WHERE IDENTIFIER = 'solr.indexing.query.ruleEngineFields'
-EOL-
UPDATE SYSTEM_CONFIGS 
SET VALUE = 'id directory document_name author creation_date_millisecond last_modified_date_millisecond folder_url' WHERE IDENTIFIER = 'solr.indexing.query.webUIFields'
-EOL-
UPDATE DOCUMENT_RECORDS
SET REPOSITORY_TYPE = 'SHARED FOLDER' WHERE REPOSITORY_TYPE IS NULL
-EOL-
CREATE TABLE [dbo].[EXCLUDED_METADATA_FIELDS](
	[FIELD_NAME] [nvarchar](100) NOT NULL,
	PRIMARY KEY CLUSTERED(
		[FIELD_NAME] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
		ON [PRIMARY]
) ON [PRIMARY]
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('AuthorId')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('CheckInComment')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('CheckOutType')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('CheckoutUserId')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('ContentTag')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('ContentTypeId')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('Created')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('CustomizedPageStatus')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('EditorId')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('Exists')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('FileSystemObjectType')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('MajorVersion')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('MinorVersion')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('Modified')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('OData__CopySource')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('OData__UIVersionString')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('UIVersion')
-EOL-
INSERT INTO EXCLUDED_METADATA_FIELDS (FIELD_NAME)
VALUES ('UIVersionLabel')
-EOL-
CREATE TABLE [dbo].[SOURCE_AUTHENTICATION](
	[ID] [bigint] NOT NULL,
	[NAME] [nvarchar](256) NOT NULL,
	[DOMAIN_NAME] [nvarchar](100) NOT NULL,
	[USERNAME] [nvarchar](100) NOT NULL,
	[PASSWORD] [nvarchar](256) NOT NULL,
	[CREATED_ON] [datetime2](7) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[MODIFIED_ON] [datetime2](7) NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT UC_SA_NAME UNIQUE ([NAME]),
	CONSTRAINT UC_SA_DOMAIN_USERNAME UNIQUE ([DOMAIN_NAME],[USERNAME]),
	PRIMARY KEY CLUSTERED(
		[ID] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
		ON [PRIMARY]
) ON [PRIMARY]
-EOL-
ALTER TABLE [dbo].[REPO_FOLDERS] ADD [REPOSITORY_TYPE] [nvarchar](30) NOT NULL DEFAULT('SHARED FOLDER')
-EOL-
ALTER TABLE [dbo].[REPO_FOLDERS] ADD [SOURCE_AUTHENTICATION_ID] [bigint] NULL
-EOL-
ALTER TABLE [dbo].[REPO_FOLDERS] WITH CHECK ADD CONSTRAINT [FK_SOURCE_AUTHENTICATION_4_REPO_FOLDERS] FOREIGN KEY([SOURCE_AUTHENTICATION_ID])
REFERENCES [dbo].[SOURCE_AUTHENTICATION] ([ID]) ON DELETE CASCADE
-EOL-
ALTER TABLE [dbo].[REPO_FOLDERS] CHECK CONSTRAINT [FK_SOURCE_AUTHENTICATION_4_REPO_FOLDERS]
-EOL-
ALTER TABLE [dbo].[ACTION_PLUGINS] ADD [REPOSITORY_TYPE] [nvarchar](30) NOT NULL DEFAULT('SHARED FOLDER')
-EOL-
UPDATE [dbo].[ACTION_PLUGINS] SET CLASS_NAME = 'com.nextlabs.smartclassifier.plugin.action.sharedfolders.copy.CopyFile', NAME='COPY_FILE (SHARED FOLDER)'
WHERE ID = 1512300900000001
-EOL-
UPDATE [dbo].[ACTION_PLUGINS] SET CLASS_NAME = 'com.nextlabs.smartclassifier.plugin.action.sharedfolders.delete.DeleteFile', NAME='DELETE_FILE (SHARED FOLDER)'
WHERE ID = 1512300900000003
-EOL-
UPDATE [dbo].[ACTION_PLUGINS] SET CLASS_NAME = 'com.nextlabs.smartclassifier.plugin.action.sharedfolders.encrypt.EncryptFile', NAME='ENCRYPT_FILE (SHARED FOLDER)'
WHERE ID = 1512300900000005
-EOL-
UPDATE [dbo].[ACTION_PLUGINS] SET CLASS_NAME = 'com.nextlabs.smartclassifier.plugin.action.sharedfolders.move.MoveFile', NAME='MOVE_FILE (SHARED FOLDER)'
WHERE ID = 1512300900000006
-EOL-
UPDATE [dbo].[ACTION_PLUGINS] SET CLASS_NAME = 'com.nextlabs.smartclassifier.plugin.action.sharedfolders.removetag.RemoveTag', NAME='REMOVE_TAG (SHARED FOLDER)'
WHERE ID = 1512300900000008
-EOL-
UPDATE [dbo].[ACTION_PLUGINS] SET CLASS_NAME = 'com.nextlabs.smartclassifier.plugin.action.sharedfolders.addtag.AddTag', NAME='ADD_TAG (SHARED FOLDER)'
WHERE ID = 1512300900000009
-EOL-
UPDATE [dbo].[ACTION_PLUGINS] SET CLASS_NAME = 'com.nextlabs.smartclassifier.plugin.action.sharedfolders.mail.SendEmail', NAME='EMAIL_NOTIFICATION (SHARED FOLDER)'
WHERE ID = 1512300900000010
-EOL-
UPDATE [dbo].[ACTION_PLUGINS] SET CLASS_NAME = 'com.nextlabs.smartclassifier.plugin.action.sharedfolders.decrypt.DecryptFile', NAME='DECRYPT_FILE (SHARED FOLDER)'
WHERE ID = 1512300900000011
-EOL-
INSERT INTO ACTION_PLUGINS (ID, DISPLAY_ORDER, CLASS_NAME, NAME, DISPLAY_NAME, DESCRIPTION, REPOSITORY_TYPE, FIRE_ONCE_PER_RULE)
VALUES (1512300900000012, 11, 'com.nextlabs.smartclassifier.plugin.action.sharepoint.copy.CopyFile', 'COPY_FILE (SHAREPOINT)', 'Copy', 'Copy given file(s) to defined target folder.', 'SHAREPOINT', 0)
-EOL-
INSERT INTO ACTION_PLUGINS (ID, DISPLAY_ORDER, CLASS_NAME, NAME, DISPLAY_NAME, DESCRIPTION, REPOSITORY_TYPE, FIRE_ONCE_PER_RULE)
VALUES (1512300900000013, 12, 'com.nextlabs.smartclassifier.plugin.action.sharepoint.move.MoveFile', 'MOVE_FILE (SHAREPOINT)', 'Move', 'Move given file(s) to the destination folder', 'SHAREPOINT', 0)
-EOL-
INSERT INTO ACTION_PLUGINS (ID, DISPLAY_ORDER, CLASS_NAME, NAME, DISPLAY_NAME, DESCRIPTION, REPOSITORY_TYPE, FIRE_ONCE_PER_RULE)
VALUES (1512300900000014, 13, 'com.nextlabs.smartclassifier.plugin.action.sharepoint.delete.DeleteFile', 'DELETE_FILE (SHAREPOINT)', 'Delete', 'Delete file or a folder.', 'SHAREPOINT', 0)
-EOL-
INSERT INTO ACTION_PLUGINS (ID, DISPLAY_ORDER, CLASS_NAME, NAME, DISPLAY_NAME, DESCRIPTION, REPOSITORY_TYPE, FIRE_ONCE_PER_RULE)
VALUES (1512300900000015, 14, 'com.nextlabs.smartclassifier.plugin.action.sharepoint.addtag.AddTag', 'ADD_TAG (SHAREPOINT)', 'Classify', 'Add specified tag(s) to given file(s).', 'SHAREPOINT', 0)
-EOL-
INSERT INTO ACTION_PLUGINS (ID, DISPLAY_ORDER, CLASS_NAME, NAME, DISPLAY_NAME, DESCRIPTION, REPOSITORY_TYPE, FIRE_ONCE_PER_RULE)
VALUES (1512300900000016, 15, 'com.nextlabs.smartclassifier.plugin.action.sharepoint.setcolumnvalue.SetColumnValue', 'SET_COLUMN_VALUE (SHAREPOINT)', 'Set Column Value', 'Set a column value in SharePoint library', 'SHAREPOINT', 0)
-EOL-
INSERT INTO ACTION_PLUGINS (ID, DISPLAY_ORDER, CLASS_NAME, NAME, DISPLAY_NAME, DESCRIPTION, REPOSITORY_TYPE, FIRE_ONCE_PER_RULE)
VALUES (1512300900000017, 16, 'com.nextlabs.smartclassifier.plugin.action.sharepoint.removetag.RemoveTag', 'REMOVE_TAG (SHAREPOINT)', 'Remove Classification', 'Remove specified tag(s) from given file(s).', 'SHAREPOINT', 0)
-EOL-
INSERT INTO ACTION_PLUGINS (ID, DISPLAY_ORDER, CLASS_NAME, NAME, DISPLAY_NAME, DESCRIPTION, REPOSITORY_TYPE, FIRE_ONCE_PER_RULE)
VALUES (1512300900000018, 17, 'com.nextlabs.smartclassifier.plugin.action.sharepoint.protect.EncryptFile', 'ENCRYPT_FILE (SHAREPOINT)', 'Protect', 'Encrypt given file(s) with NextLabs library.', 'SHAREPOINT', 0)
-EOL-
INSERT INTO ACTION_PLUGINS (ID, DISPLAY_ORDER, CLASS_NAME, NAME, DISPLAY_NAME, DESCRIPTION, REPOSITORY_TYPE, FIRE_ONCE_PER_RULE)
VALUES (1512300900000019, 18, 'com.nextlabs.smartclassifier.plugin.action.sharepoint.removeprotection.DecryptFile', 'DECRYPT_FILE (SHAREPOINT)', 'Remove Protection', 'Decrypt NXL file(s) with NextLabs library.', 'SHAREPOINT', 0)
-EOL-
INSERT INTO ACTION_PLUGINS (ID, DISPLAY_ORDER, CLASS_NAME, NAME, DISPLAY_NAME, DESCRIPTION, REPOSITORY_TYPE, FIRE_ONCE_PER_RULE)
VALUES (1512300900000020, 19, 'com.nextlabs.smartclassifier.plugin.action.sharepoint.notify.EMailNotify', 'EMAIL_NOTIFICATION (SHAREPOINT)', 'Email Notification', 'Send e-mail notification to indicate the list of files matching the critertia.', 'SHAREPOINT', 1)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301601000002, 1512300900000001, 2, 'P', 0, 0, 'Boolean', 'Overwrite if file exist in destination folder', 'overwrite', 0)
-EOL-
UPDATE [dbo].[ACTION_PLUGIN_PARAMS] SET DISPLAY_ORDER = 2
WHERE ID = 1512301605000009
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301606000002, 1512300900000006, 2, 'P', 0, 0, 'Boolean', 'Overwrite if file exist in destination folder', 'overwrite', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301611000002, 1512300900000011, 2, 'P', 0, 0, 'Boolean', 'Overwrite if file exist in destination folder', 'overwrite', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301615000001, 1512300900000015, 1, 'T', 1, 1, 'String', 'Metadata', 'tag', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301612000001, 1512300900000012, 1, 'P', 0, 0, 'String', 'Destination folder', 'target', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301612000002, 1512300900000012, 2, 'P', 0, 0, 'Boolean', 'Overwrite if file exist in destination folder', 'overwrite', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301618000001, 1512300900000018, 1, 'P', 0, 0, 'Boolean', 'Delete original file', 'delete-original-file', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301618000002, 1512300900000018, 2, 'T', 1, 1, 'String', 'Metadata', 'tag', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER, FIXED_VALUE)
VALUES (1512301620000001, 1512300900000020, 1, 'P', 0, 0, 'String', 'Folder for storing snapshot files (must be on the UI machine)', 'snapshots-folder', 1, '\\@hostname\')
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301620000002, 1512300900000020, 2, 'P', 1, 0, 'Email', 'Recipient', 'email-recipient', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301620000003, 1512300900000020, 3, 'P', 0, 0, 'String', 'Subject', 'email-subject', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301620000004, 1512300900000020, 4, 'P', 0, 0, 'Text', 'Content', 'email-content', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301613000001, 1512300900000013, 1, 'P', 0, 0, 'String', 'Destination folder', 'target', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301613000002, 1512300900000013, 2, 'P', 0, 0, 'Boolean', 'Overwrite if file exist in destination folder', 'overwrite', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301617000001, 1512300900000017, 1, 'T', 1, 0, 'String', 'Metadata to remove', 'tag', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301619000001, 1512300900000019, 1, 'P', 0, 0, 'Boolean', 'Delete original file', 'delete-original-file', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301619000002, 1512300900000019, 2, 'P', 0, 0, 'Boolean', 'Overwrite if file exist in destination folder', 'overwrite', 0)
-EOL-
INSERT INTO ACTION_PLUGIN_PARAMS (ID, ACTION_PLUGIN_ID, DISPLAY_ORDER, PARAM_TYPE, COLLECTIONS, KEY_VALUE, DATA_TYPE, LABEL, IDENTIFIER, FIXED_PARAMETER)
VALUES (1512301616000001, 1512300900000016, 1, 'T', 0, 1, 'String', 'Column', 'tag', 0)
-EOL-
UPDATE T1
SET T1.[COMPONENT_ID] = T2.[ID]
FROM [dbo].[EXECUTION_WINDOW_ASSOCIATIONS] AS T1
INNER JOIN [dbo].[EXTRACTORS] AS T2 ON T1.[HOSTNAME] = T2.[HOSTNAME]
WHERE T1.[COMPONENT_ID] = '0' AND T1.[COMPONENT_TYPE] = 'E'
-EOL-
UPDATE T1
SET T1.[COMPONENT_ID] = T2.[ID]
FROM [dbo].[EXECUTION_WINDOW_ASSOCIATIONS] AS T1
INNER JOIN [dbo].[RULE_ENGINES] AS T2 ON T1.[HOSTNAME] = T2.[HOSTNAME]
WHERE T1.[COMPONENT_ID] = '0' AND T1.[COMPONENT_TYPE] = 'R'	
-EOL-
ALTER TABLE [dbo].[EXECUTION_WINDOW_ASSOCIATIONS] DROP CONSTRAINT [UC_EXECUTION_WINDOW_ASSOCIATION]
-EOL-
ALTER TABLE [dbo].[EXECUTION_WINDOW_ASSOCIATIONS] DROP COLUMN [HOSTNAME]
-EOL-
ALTER TABLE [dbo].[EXECUTION_WINDOW_ASSOCIATIONS] ADD CONSTRAINT UC_EXECUTION_WINDOW_ASSOCIATION UNIQUE ([COMPONENT_ID], [COMPONENT_TYPE], [EXECUTION_WINDOW_SET_ID])
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('file_id', 24, 'Document ID', 'STRING', 'STRING', 0)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('sp_author', 25, 'SharePoint Author', 'STRING', 'STRING', 1)
-EOL-
INSERT INTO METADATA_FIELDS (FIELD_NAME, DISPLAY_ORDER, DISPLAY_NAME, UI_DATA_TYPE, STORAGE_DATA_TYPE, VISIBLE)
VALUES ('sp_last_author', 26, 'SharePoint Last Author', 'STRING', 'STRING', 1)
-EOL-