INSERT INTO WATCHERS (ID, NAME, HOSTNAME, JMS_PROFILE_ID, FILE_MONITOR_COUNT, CONFIG_RELOAD_INTERVAL, CREATED_ON)
VALUES (id, 'File Watcher (@hostname)', '@hostname', jms_id, 4, 300, CONVERT (datetime2,GETDATE(),120));
-EOL-