DELETE FROM SYSTEM_CONFIGS WHERE IDENTIFIER = 'smart.classifier.url'
-EOL-
DELETE FROM SYSTEM_CONFIGS WHERE IDENTIFIER = 'login.url'
-EOL-
DELETE FROM SYSTEM_CONFIGS WHERE IDENTIFIER = 'logout.url'
-EOL-