#!/bin/bash
#
# DESCRIPTION
#	Invoke release build
#
# USAGE:
#	Steps to invoke this script.
#		export NLEXTERNALDIR=<path>
#		export BUILD_NUMBER=<#>
#		source setEnv
#		./buildRelease
#
# HUDSON BUILD:
#	cd $WORKSPACE
#	export NLEXTERNALDIR=c:/hudson/jobs/source_main_external/workspace
#	source setEnv
#	./buildRelease
#
# DEBUG:
#	To debug ANT problems, add -v option to an ANT command. For example:
#		$ANT -v -f scripts/build_xlib.xml

export JAVA_HOME=$NLEXTERNALDIR/j2sdk/jdk1.7.0_75
export ANT_HOME=$NLEXTERNALDIR/apache-ant/apache-ant-1.9.4

ANT=$ANT_HOME/bin/ant
LOG_FILE=buildRelease.log
BUILD_MANIFEST_FILE=build.manifest

(
set -x
# Extract Perforce Workspace and Hudson info (only if running on Hudson)
if [ -f ../config.xml ]; then
	scripts/getPerforceWorkspace.pl ../config.xml
fi

# Prepare environment
./configure --type=release || exit $?
source build.config

# Compile code and build installers
export ANT_OPTS="-Xmx1024M"
export ANT_ARGS="-Dnlbuildroot=$NLBUILDROOT -Dnlexternaldir=$NLEXTERNALDIR -Dversion_str=$VERSION_STR -Dversion_build_short=$VERSION_BUILD_SHORT -Dbuild_date_long=$BUILD_DATE_LONG"

# Prepare dependencies
$ANT -f scripts/build_xlib.xml || exit $?

# Perform compilation
$ANT -f scripts/build_compile.xml || exit $?

set +x
) 2>&1 | tee $LOG_FILE

exit ${PIPESTATUS[0]}

## EOF ##
