#!/bin/bash
#
# DESCRIPTION
#	Invoke release build
#
# USAGE:
#	Steps to invoke this script.
#		export NLEXTERNALDIR=<path>
#		export BUILD_NUMBER=<#>
#		source setEnv
#		./buildRelease
#
# HUDSON BUILD:
#	cd $WORKSPACE
#	export NLEXTERNALDIR=c:/hudson/jobs/source_main_external/workspace
#	source setEnv
#	./buildRelease
#
# DEBUG:
#	To debug ANT problems, add -v option to an ANT command. For example:
#		$ANT -v -f scripts/build_xlib.xml

export ANT_HOME=$NLEXTERNALDIR/apache-ant/apache-ant-1.10.7
export JAVA_HOME=$NLEXTERNALDIR/openjdk/jdk-11.0.14.1+1-win64
export NSIS_HOME=${NLEXTERNALDIR}/nsis/3.0b1

ANT=${ANT_HOME}/bin/ant
LOG_FILE=buildRelease.log
BUILD_MANIFEST_FILE=build.manifest

(
set -x
# Extract Perforce Workspace and Hudson info (only if running on Hudson)
if [ -f ../../config.xml ]; then
	scripts/getPerforceWorkspace.pl ../../config.xml
fi

# Prepare environment
./configure --type=release || exit $?
source build.config

# Compile code and build installers
export ANT_OPTS="-Xmx1024M"
export ANT_ARGS="-Dnlbuildroot=${NLBUILDROOT} -Dnlexternaldir=${NLEXTERNALDIR} -Dversion_str=${VERSION_STR} -Dversion_build_short=${VERSION_BUILD_SHORT} -Dbuild_date_long=${BUILD_DATE_LONG}"

# Perform packaging
source ./sc_packaging_versioninfo.txt
echo "[INFO] PRODUCTNAME: ${PRODUCTNAME}"
echo "[INFO] PRODUCTCAPTION: ${PRODUCTCAPTION}"
echo "[INFO] PRODUCT_INSTALLER_FILENAME: ${PRODUCT_INSTALLER_FILENAME}"
${NSIS_HOME}/bin/makensis.exe -V4 build.nsi || exit -?

# Publish the installer to BODA
${ANT} -f scripts/build_publish.xml sc || exit $?

# Finally publish the manifest to BODA
scripts/createBuildManifest.pl ${LOG_FILE} > ${BUILD_MANIFEST_FILE} || exit $?
${ANT} -f scripts/build_publish.xml manifest || exit $?

set +x

echo
echo
echo "####################### BUILD MANIFEST CONTENTS ########################"
cat ${BUILD_MANIFEST_FILE}
echo "########################################################################"
) 2>&1 | tee $LOG_FILE

exit ${PIPESTATUS[0]}

## EOF ##
